"""
Hostel Mess Admin Portal
Master Control: All generated QRs, dishes added by cook on any given day,
student turnout (how many polled vs didn't poll), what each student chose,
and comprehensive visual analytics.
"""

import os
import csv
from datetime import datetime
import tkinter as tk
from tkinter import messagebox, filedialog
import customtkinter as ctk

from matplotlib.figure import Figure
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg

from theme import *
from database import (
    get_all_polls, 
    get_all_students, 
    get_admin_detailed_data, 
    get_dishes_by_date, 
    get_audit_logs
)
from qr_manager import QRManager, QR_STORAGE_DIR

class AdminView(ctk.CTkFrame):
    
    def __init__(self, parent, on_logout):
        super().__init__(parent, fg_color=COLOR_BG_MAIN)
        self.parent = parent
        self.on_logout = on_logout
        
        self.polls = get_all_polls()
        self.selected_poll_id = self.polls[0]['id'] if self.polls else None
        
        self.setup_ui()
        
    def setup_ui(self):
        # 1. Top Navbar
        navbar = ctk.CTkFrame(self, fg_color=COLOR_BG_CARD, height=65, corner_radius=0, border_width=1, border_color=COLOR_BORDER_LIGHT)
        navbar.pack(fill="x", side="top")
        navbar.pack_propagate(False)
        
        # Left brand
        brand_frame = ctk.CTkFrame(navbar, fg_color="transparent")
        brand_frame.pack(side="left", padx=25)
        
        icon_lbl = ctk.CTkLabel(brand_frame, text="🛡️", font=("Segoe UI", 24))
        icon_lbl.pack(side="left", padx=(0, 10))
        
        brand_title = ctk.CTkLabel(brand_frame, text="Hostel Administration Master Dashboard", font=FONT_TITLE, text_color=COLOR_PRIMARY_DARK)
        brand_title.pack(side="left")
        
        pill = ctk.CTkFrame(brand_frame, fg_color=COLOR_WARNING_LIGHT, corner_radius=CORNER_RADIUS_PILL)
        pill.pack(side="left", padx=12)
        ctk.CTkLabel(pill, text="FULL AUDIT & DATA ACCESS", font=FONT_CAPTION_BOLD, text_color=COLOR_WARNING).pack(padx=10, pady=2)
        
        # Right actions
        nav_right = ctk.CTkFrame(navbar, fg_color="transparent")
        nav_right.pack(side="right", padx=25)
        
        export_btn = ctk.CTkButton(
            nav_right,
            text="📥 Export Report (CSV)",
            font=FONT_BODY_BOLD,
            fg_color=COLOR_LIGHT_ACCENT,
            hover_color=COLOR_LIGHT_ACCENT_HOVER,
            text_color=COLOR_DEEP_OCEAN,
            corner_radius=CORNER_RADIUS_BUTTON,
            command=self.export_csv_report
        )
        export_btn.pack(side="left", padx=(0, 12))
        
        logout_btn = ctk.CTkButton(
            nav_right,
            text="🚪 Back to Roles",
            font=FONT_BODY,
            fg_color="#F1F5F9",
            hover_color="#E2E8F0",
            text_color=COLOR_TEXT_MAIN,
            corner_radius=CORNER_RADIUS_BUTTON,
            width=120,
            command=self.on_logout
        )
        logout_btn.pack(side="right")
        
        # 2. Top Metric KPI Cards Row
        self.setup_kpi_cards()
        
        # 3. Main Tabview
        self.tabview = ctk.CTkTabview(
            self,
            fg_color="transparent",
            segmented_button_fg_color=COLOR_BG_CARD,
            segmented_button_selected_color=COLOR_PRIMARY,
            segmented_button_selected_hover_color=COLOR_PRIMARY_HOVER,
            segmented_button_unselected_color=COLOR_LIGHT_ACCENT,
            segmented_button_unselected_hover_color=COLOR_LIGHT_ACCENT_HOVER,
            text_color=COLOR_TEXT_MAIN,
            corner_radius=CORNER_RADIUS_CARD
        )
        self.tabview.pack(fill="both", expand=True, padx=25, pady=(0, 20))
        
        self.tab_turnout = self.tabview.add("👥  Student Turnout (Polled vs Didn't Poll)")
        self.tab_qr_dishes = self.tabview.add("📱  QR History & Daily Cook Dishes")
        self.tab_charts = self.tabview.add("📈  Visual Analytics & Charts")
        self.tab_audit = self.tabview.add("📜  Security & Audit Logs")
        
        self.setup_turnout_tab()
        self.setup_qr_dishes_tab()
        self.setup_charts_tab()
        self.setup_audit_tab()
        
    def setup_kpi_cards(self):
        kpi_row = ctk.CTkFrame(self, fg_color="transparent")
        kpi_row.pack(fill="x", padx=25, pady=(15, 10))
        
        total_polls = len(self.polls)
        total_students = len(get_all_students())
        
        # Calculate active turnout
        active_turnout = 0
        if self.polls:
            data = get_admin_detailed_data(self.polls[0]['id'])
            active_turnout = data['turnout_pct'] if data else 0
            
        self.create_metric_card(kpi_row, "Total QR Polls", f"{total_polls}", "Generated by cook", "📱", COLOR_PRIMARY)
        self.create_metric_card(kpi_row, "Hostel Students", f"{total_students}", "Registered in hostel", "🎓", COLOR_PRIMARY_DARK)
        self.create_metric_card(kpi_row, "Current Turnout", f"{active_turnout}%", "Student participation", "📊", COLOR_SUCCESS)
        self.create_metric_card(kpi_row, "Today's Status", "Online", datetime.now().strftime("%d %b %Y"), "⚡", COLOR_SPECIAL)
        
    def create_metric_card(self, parent, title, value, subtitle, icon, icon_color):
        card = ctk.CTkFrame(parent, fg_color=COLOR_BG_CARD, border_width=1, border_color=COLOR_BORDER, corner_radius=CORNER_RADIUS_CARD, height=85)
        card.pack(side="left", fill="both", expand=True, padx=6)
        card.pack_propagate(False)
        
        row = ctk.CTkFrame(card, fg_color="transparent")
        row.pack(fill="both", expand=True, padx=16, pady=12)
        
        left = ctk.CTkFrame(row, fg_color="transparent")
        left.pack(side="left")
        
        ctk.CTkLabel(left, text=title, font=FONT_CAPTION_BOLD, text_color=COLOR_TEXT_MUTED).pack(anchor="w")
        ctk.CTkLabel(left, text=value, font=FONT_TITLE, text_color=COLOR_PRIMARY_DARK).pack(anchor="w")
        ctk.CTkLabel(left, text=subtitle, font=FONT_CAPTION, text_color=COLOR_TEXT_LIGHT).pack(anchor="w")
        
        ctk.CTkLabel(row, text=icon, font=("Segoe UI", 28)).pack(side="right", padx=(0, 5))
        
    # --- TAB 1: TURNOUT (POLLED VS DIDN'T POLL) ---
    def setup_turnout_tab(self):
        container = ctk.CTkFrame(self.tab_turnout, fg_color="transparent")
        container.pack(fill="both", expand=True, padx=10, pady=10)
        
        # Selector bar
        sel_bar = ctk.CTkFrame(container, fg_color=COLOR_BG_CARD, border_width=1, border_color=COLOR_BORDER, corner_radius=CORNER_RADIUS_CARD)
        sel_bar.pack(fill="x", pady=(0, 10))
        
        sb_row = ctk.CTkFrame(sel_bar, fg_color="transparent")
        sb_row.pack(fill="x", padx=20, pady=10)
        
        ctk.CTkLabel(sb_row, text="Select QR Session:", font=FONT_BODY_BOLD, text_color=COLOR_TEXT_MAIN).pack(side="left", padx=(0, 10))
        
        poll_options = [f"{p['id']} - {p['title']} ({p['date']} {p['meal_type']})" for p in self.polls] if self.polls else ["No polls"]
        self.turnout_poll_var = ctk.StringVar(value=poll_options[0] if poll_options else "")
        self.turnout_poll_menu = ctk.CTkOptionMenu(
            sb_row,
            values=poll_options,
            variable=self.turnout_poll_var,
            fg_color=COLOR_LIGHT_ACCENT,
            text_color=COLOR_DEEP_OCEAN,
            button_color=COLOR_PRIMARY,
            button_hover_color=COLOR_PRIMARY_HOVER,
            width=380,
            command=self.on_turnout_poll_changed
        )
        self.turnout_poll_menu.pack(side="left")
        
        # Search box
        self.search_entry = ctk.CTkEntry(
            sb_row,
            placeholder_text="🔍 Search student name, room, dish...",
            fg_color=COLOR_BG_CARD_ALT,
            border_color=COLOR_BORDER,
            width=240
        )
        self.search_entry.pack(side="right")
        self.search_entry.bind("<KeyRelease>", lambda e: self.filter_turnout_tables())
        
        # KPI Bar for selected poll
        self.kpi_banner = ctk.CTkFrame(container, fg_color=COLOR_LIGHT_ACCENT, border_width=1, border_color=COLOR_BORDER, corner_radius=CORNER_RADIUS_CARD)
        self.kpi_banner.pack(fill="x", pady=(0, 10))
        
        self.kpi_banner_lbl = ctk.CTkLabel(self.kpi_banner, text="", font=FONT_BODY_BOLD, text_color=COLOR_DEEP_OCEAN)
        self.kpi_banner_lbl.pack(padx=20, pady=10)
        
        # Split Tables (Left: Polled / What they chose; Right: Didn't poll)
        tables_row = ctk.CTkFrame(container, fg_color="transparent")
        tables_row.pack(fill="both", expand=True)
        
        # Left Table: Polled
        self.polled_frame = ctk.CTkFrame(tables_row, fg_color=COLOR_BG_CARD, border_width=1, border_color=COLOR_BORDER, corner_radius=CORNER_RADIUS_CARD)
        self.polled_frame.pack(side="left", fill="both", expand=True, padx=(0, 6))
        
        p_head = ctk.CTkFrame(self.polled_frame, fg_color=COLOR_SUCCESS_LIGHT, corner_radius=CORNER_RADIUS_CARD, height=40)
        p_head.pack(fill="x", padx=8, pady=8)
        p_head.pack_propagate(False)
        self.polled_head_lbl = ctk.CTkLabel(p_head, text="✅ Students Who Polled & Their Choices", font=FONT_HEADING, text_color="#065F46")
        self.polled_head_lbl.pack(side="left", padx=12)
        
        self.polled_scroll = ctk.CTkScrollableFrame(self.polled_frame, fg_color="transparent")
        self.polled_scroll.pack(fill="both", expand=True, padx=8, pady=(0, 8))
        
        # Right Table: Didn't Poll
        self.non_polled_frame = ctk.CTkFrame(tables_row, fg_color=COLOR_BG_CARD, border_width=1, border_color=COLOR_BORDER, corner_radius=CORNER_RADIUS_CARD)
        self.non_polled_frame.pack(side="right", fill="both", expand=True, padx=(6, 0))
        
        np_head = ctk.CTkFrame(self.non_polled_frame, fg_color=COLOR_DANGER_LIGHT, corner_radius=CORNER_RADIUS_CARD, height=40)
        np_head.pack(fill="x", padx=8, pady=8)
        np_head.pack_propagate(False)
        self.non_polled_head_lbl = ctk.CTkLabel(np_head, text="❌ Students Who Didn't Poll", font=FONT_HEADING, text_color="#991B1B")
        self.non_polled_head_lbl.pack(side="left", padx=12)
        
        self.non_polled_scroll = ctk.CTkScrollableFrame(self.non_polled_frame, fg_color="transparent")
        self.non_polled_scroll.pack(fill="both", expand=True, padx=8, pady=(0, 8))
        
        self.current_poll_data = None
        self.render_turnout_data()
        
    def on_turnout_poll_changed(self, val):
        if val and " - " in val:
            self.selected_poll_id = val.split(" - ")[0].strip()
            self.render_turnout_data()
            
    def render_turnout_data(self):
        if not self.selected_poll_id:
            return
            
        data = get_admin_detailed_data(self.selected_poll_id)
        self.current_poll_data = data
        if not data:
            return
            
        poll = data['poll']
        self.kpi_banner_lbl.configure(
            text=f"📊 Session: {poll['title']}  •  Total Students: {data['total_hostel_students']}  •  "
                 f"Polled: {data['polled_count']} ({data['turnout_pct']}%)  •  "
                 f"Didn't Poll: {data['non_polled_count']}  •  "
                 f"Leading Choice: 👑 {data['winner']}"
        )
        
        self.polled_head_lbl.configure(text=f"✅ Students Who Polled ({data['polled_count']}) & Their Choices")
        self.non_polled_head_lbl.configure(text=f"❌ Students Who Didn't Poll ({data['non_polled_count']})")
        
        self.filter_turnout_tables()
        
    def filter_turnout_tables(self):
        if not self.current_poll_data:
            return
            
        search_query = self.search_entry.get().strip().lower()
        
        # 1. Populate Polled Students
        for w in self.polled_scroll.winfo_children():
            w.destroy()
            
        polled = self.current_poll_data['polled_students']
        filtered_polled = [
            s for s in polled
            if not search_query or (search_query in s['name'].lower() or search_query in s['student_id'].lower() or search_query in s['room_no'].lower() or search_query in s['chosen_dish'].lower())
        ]
        
        if not filtered_polled:
            ctk.CTkLabel(self.polled_scroll, text="No polled students found.", font=FONT_CAPTION, text_color=COLOR_TEXT_MUTED).pack(pady=15)
        else:
            for s in filtered_polled:
                row = ctk.CTkFrame(self.polled_scroll, fg_color=COLOR_BG_CARD_ALT, border_width=1, border_color=COLOR_BORDER_LIGHT, corner_radius=8)
                row.pack(fill="x", pady=3)
                
                r_top = ctk.CTkFrame(row, fg_color="transparent")
                r_top.pack(fill="x", padx=10, pady=(6, 2))
                
                ctk.CTkLabel(r_top, text=f"{s['name']} ({s['student_id']})", font=FONT_BODY_BOLD, text_color=COLOR_TEXT_MAIN).pack(side="left")
                ctk.CTkLabel(r_top, text=f"Room: {s['room_no']} • {s['block']}", font=FONT_CAPTION_BOLD, text_color=COLOR_PRIMARY_DARK).pack(side="right")
                
                r_bottom = ctk.CTkFrame(row, fg_color="transparent")
                r_bottom.pack(fill="x", padx=10, pady=(0, 6))
                
                dish_pill = ctk.CTkFrame(r_bottom, fg_color=COLOR_LIGHT_ACCENT, corner_radius=6)
                dish_pill.pack(side="left")
                ctk.CTkLabel(dish_pill, text=f"Voted: {s['chosen_dish']}", font=FONT_CAPTION_BOLD, text_color=COLOR_DEEP_OCEAN).pack(padx=6, pady=1)
                
                v_time = s['voted_at'].split(" ")[-1] if " " in s['voted_at'] else s['voted_at']
                ctk.CTkLabel(r_bottom, text=f"at {v_time}", font=FONT_CAPTION, text_color=COLOR_TEXT_LIGHT).pack(side="right")
                
        # 2. Populate Non-Polled Students
        for w in self.non_polled_scroll.winfo_children():
            w.destroy()
            
        non_polled = self.current_poll_data['non_polled_students']
        filtered_np = [
            s for s in non_polled
            if not search_query or (search_query in s['name'].lower() or search_query in s['student_id'].lower() or search_query in s['room_no'].lower() or search_query in s.get('department', '').lower())
        ]
        
        if not filtered_np:
            ctk.CTkLabel(self.non_polled_scroll, text="No students match criteria.", font=FONT_CAPTION, text_color=COLOR_TEXT_MUTED).pack(pady=15)
        else:
            for s in filtered_np:
                row = ctk.CTkFrame(self.non_polled_scroll, fg_color=COLOR_BG_CARD_ALT, border_width=1, border_color=COLOR_BORDER_LIGHT, corner_radius=8)
                row.pack(fill="x", pady=3)
                
                r_top = ctk.CTkFrame(row, fg_color="transparent")
                r_top.pack(fill="x", padx=10, pady=(6, 2))
                
                ctk.CTkLabel(r_top, text=f"{s['name']} ({s['student_id']})", font=FONT_BODY_BOLD, text_color=COLOR_TEXT_MAIN).pack(side="left")
                ctk.CTkLabel(r_top, text=f"Room: {s['room_no']} • {s['block']}", font=FONT_CAPTION_BOLD, text_color=COLOR_DANGER).pack(side="right")
                
                r_bottom = ctk.CTkFrame(row, fg_color="transparent")
                r_bottom.pack(fill="x", padx=10, pady=(0, 6))
                
                ctk.CTkLabel(r_bottom, text=f"Dept: {s.get('department', 'General')}", font=FONT_CAPTION, text_color=COLOR_TEXT_MUTED).pack(side="left")
                if s.get('phone'):
                    ctk.CTkLabel(r_bottom, text=f"📞 {s['phone']}", font=FONT_CAPTION, text_color=COLOR_TEXT_LIGHT).pack(side="right")

    # --- TAB 2: QR HISTORY & DAILY COOK DISHES ---
    def setup_qr_dishes_tab(self):
        container = ctk.CTkFrame(self.tab_qr_dishes, fg_color="transparent")
        container.pack(fill="both", expand=True, padx=10, pady=10)
        
        # Left pane: QR list
        left_pane = ctk.CTkFrame(container, fg_color=COLOR_BG_CARD, border_width=1, border_color=COLOR_BORDER, corner_radius=CORNER_RADIUS_CARD, width=330)
        left_pane.pack(side="left", fill="y", padx=(0, 10))
        left_pane.pack_propagate(False)
        
        lp_header = ctk.CTkFrame(left_pane, fg_color=COLOR_LIGHT_ACCENT, height=45, corner_radius=CORNER_RADIUS_CARD)
        lp_header.pack(fill="x", padx=10, pady=10)
        ctk.CTkLabel(lp_header, text="📱 Generated QR Codes History", font=FONT_SUBTITLE, text_color=COLOR_PRIMARY_DARK).pack(side="left", padx=15, pady=10)
        
        self.qr_scroll = ctk.CTkScrollableFrame(left_pane, fg_color="transparent")
        self.qr_scroll.pack(fill="both", expand=True, padx=10, pady=(0, 10))
        
        # Right pane: Full dishes detail added by cook on that day
        self.daily_dishes_pane = ctk.CTkScrollableFrame(container, fg_color=COLOR_BG_CARD, border_width=1, border_color=COLOR_BORDER, corner_radius=CORNER_RADIUS_CARD)
        self.daily_dishes_pane.pack(side="right", fill="both", expand=True)
        
        self.render_qr_history()
        
    def render_qr_history(self):
        for w in self.qr_scroll.winfo_children():
            w.destroy()
            
        polls = get_all_polls()
        for p in polls:
            card = ctk.CTkFrame(self.qr_scroll, fg_color=COLOR_BG_CARD_ALT, border_width=1, border_color=COLOR_BORDER_LIGHT, corner_radius=10)
            card.pack(fill="x", pady=5)
            
            top_row = ctk.CTkFrame(card, fg_color="transparent")
            top_row.pack(fill="x", padx=10, pady=(8, 2))
            
            is_active = p['status'] == 'ACTIVE'
            badge = ctk.CTkFrame(top_row, fg_color=COLOR_SUCCESS_LIGHT if is_active else COLOR_DANGER_LIGHT, corner_radius=6)
            badge.pack(side="left")
            ctk.CTkLabel(badge, text=p['status'], font=FONT_CAPTION_BOLD, text_color=COLOR_SUCCESS if is_active else COLOR_DANGER).pack(padx=6, pady=1)
            
            ctk.CTkLabel(top_row, text=p['date'], font=FONT_CAPTION_BOLD, text_color=COLOR_TEXT_MUTED).pack(side="right")
            
            ctk.CTkLabel(card, text=p['title'], font=FONT_BODY_BOLD, text_color=COLOR_TEXT_MAIN, anchor="w").pack(fill="x", padx=10, pady=2)
            ctk.CTkLabel(card, text=f"Generated by: {p['created_by']}", font=FONT_CAPTION, text_color=COLOR_TEXT_LIGHT, anchor="w").pack(fill="x", padx=10)
            
            view_btn = ctk.CTkButton(
                card,
                text="Inspect Daily Dishes & QR →",
                font=FONT_CAPTION_BOLD,
                fg_color=COLOR_LIGHT_ACCENT,
                hover_color=COLOR_LIGHT_ACCENT_HOVER,
                text_color=COLOR_DEEP_OCEAN,
                height=26,
                command=lambda pid=p['id']: self.inspect_daily_dishes(pid)
            )
            view_btn.pack(fill="x", padx=10, pady=(6, 8))
            
        if polls:
            self.inspect_daily_dishes(polls[0]['id'])
            
    def inspect_daily_dishes(self, poll_id):
        for w in self.daily_dishes_pane.winfo_children():
            w.destroy()
            
        data = get_admin_detailed_data(poll_id)
        if not data:
            return
            
        poll = data['poll']
        
        # Header banner
        header = ctk.CTkFrame(self.daily_dishes_pane, fg_color=COLOR_LIGHT_ACCENT, corner_radius=CORNER_RADIUS_CARD)
        header.pack(fill="x", padx=15, pady=(15, 10))
        
        h_top = ctk.CTkFrame(header, fg_color="transparent")
        h_top.pack(fill="x", padx=15, pady=(12, 4))
        
        ctk.CTkLabel(h_top, text=f"📅 Dishes Added on {poll['date']} ({poll['meal_type']})", font=FONT_TITLE, text_color=COLOR_PRIMARY_DARK).pack(side="left")
        ctk.CTkLabel(h_top, text=f"QR Code: {poll['id']}", font=FONT_MONO, text_color=COLOR_DEEP_OCEAN).pack(side="right")
        
        ctk.CTkLabel(
            header,
            text=f"Cook Incharge: {poll['created_by']}  •  Generated At: {poll['created_at']}  •  Scheduled Expiry: {poll['expires_at']}",
            font=FONT_BODY,
            text_color=COLOR_DEEP_OCEAN
        ).pack(anchor="w", padx=15, pady=(0, 12))
        
        # Content split: Dishes list (left) & QR Poster preview (right)
        split_row = ctk.CTkFrame(self.daily_dishes_pane, fg_color="transparent")
        split_row.pack(fill="both", expand=True, padx=15, pady=10)
        
        # Dishes Column
        dishes_col = ctk.CTkFrame(split_row, fg_color="transparent")
        dishes_col.pack(side="left", fill="both", expand=True, padx=(0, 10))
        
        ctk.CTkLabel(dishes_col, text="🍲 Cook's Selected Menu Options for this Day:", font=FONT_SUBTITLE, text_color=COLOR_PRIMARY_DARK).pack(anchor="w", pady=(0, 8))
        
        for idx, d in enumerate(data['dish_results']):
            d_card = ctk.CTkFrame(dishes_col, fg_color=COLOR_BG_CARD_ALT, border_width=1, border_color=COLOR_BORDER_LIGHT, corner_radius=10)
            d_card.pack(fill="x", pady=4)
            
            d_top = ctk.CTkFrame(d_card, fg_color="transparent")
            d_top.pack(fill="x", padx=12, pady=(10, 4))
            
            badge_bg = COLOR_SUCCESS_LIGHT if d['category'] == 'Veg' else (COLOR_DANGER_LIGHT if d['category'] == 'Non-Veg' else COLOR_SPECIAL_LIGHT)
            badge_fg = COLOR_SUCCESS if d['category'] == 'Veg' else (COLOR_DANGER if d['category'] == 'Non-Veg' else COLOR_SPECIAL)
            badge = ctk.CTkFrame(d_top, fg_color=badge_bg, corner_radius=6)
            badge.pack(side="left")
            ctk.CTkLabel(badge, text=d['category'], font=FONT_CAPTION_BOLD, text_color=badge_fg).pack(padx=6, pady=1)
            
            ctk.CTkLabel(d_top, text=f"{idx+1}. {d['name']}", font=FONT_BODY_BOLD, text_color=COLOR_TEXT_MAIN).pack(side="left", padx=10)
            ctk.CTkLabel(d_top, text=f"Votes: {d['vote_count']} ({d['percentage']}%)", font=FONT_BODY_BOLD, text_color=COLOR_TEXT_BLUE).pack(side="right")
            
            if d.get('description'):
                ctk.CTkLabel(d_card, text=d['description'], font=FONT_CAPTION, text_color=COLOR_TEXT_MUTED, anchor="w").pack(fill="x", padx=12, pady=(0, 4))
                
            cal_row = ctk.CTkFrame(d_card, fg_color="transparent")
            cal_row.pack(fill="x", padx=12, pady=(0, 8))
            ctk.CTkLabel(cal_row, text=f"Calories: {d.get('calories', 'N/A')} kcal", font=FONT_CAPTION, text_color=COLOR_TEXT_LIGHT).pack(side="left")
            if d.get('allergens'):
                ctk.CTkLabel(cal_row, text=f"Allergens: {d['allergens']}", font=FONT_CAPTION, text_color=COLOR_WARNING).pack(side="right")
                
        # QR Poster Preview Column
        qr_col = ctk.CTkFrame(split_row, fg_color=COLOR_BG_CARD_ALT, border_width=1, border_color=COLOR_BORDER_LIGHT, corner_radius=12, width=280)
        qr_col.pack(side="right", fill="y", padx=(10, 0))
        qr_col.pack_propagate(False)
        
        ctk.CTkLabel(qr_col, text="Generated QR Poster", font=FONT_HEADING, text_color=COLOR_PRIMARY_DARK).pack(pady=(12, 6))
        
        poster_file = os.path.join(QR_STORAGE_DIR, f"{poll['id']}.png")
        if not os.path.exists(poster_file):
            poster_file = QRManager.generate_qr_image(poll['id'], poll['title'], poll['meal_type'], poll['expires_at'])
            
        if os.path.exists(poster_file):
            img_ctk = QRManager.get_ctk_image(poster_file, size=(220, 260))
            ctk.CTkLabel(qr_col, image=img_ctk, text="").pack(pady=5)
            
        ctk.CTkButton(
            qr_col,
            text="💾 Download Poster",
            font=FONT_CAPTION_BOLD,
            fg_color=COLOR_PRIMARY,
            hover_color=COLOR_PRIMARY_HOVER,
            text_color=COLOR_TEXT_MAIN,
            command=lambda p=poster_file: self.save_qr_copy(p)
        ).pack(fill="x", padx=20, pady=(6, 12))

    def save_qr_copy(self, source_path):
        target = filedialog.asksaveasfilename(
            defaultextension=".png",
            filetypes=[("PNG Image", "*.png")],
            initialfile=os.path.basename(source_path)
        )
        if target:
            import shutil
            shutil.copyfile(source_path, target)
            messagebox.showinfo("Saved", "Poster saved successfully.")

    # --- TAB 3: VISUAL ANALYTICS & CHARTS ---
    def setup_charts_tab(self):
        container = ctk.CTkFrame(self.tab_charts, fg_color="transparent")
        container.pack(fill="both", expand=True, padx=10, pady=10)
        
        # Render charts for current poll
        data = get_admin_detailed_data(self.selected_poll_id) if self.selected_poll_id else None
        if not data or not data['dish_results']:
            ctk.CTkLabel(container, text="No voting data available for charts.").pack(pady=40)
            return
            
        fig = Figure(figsize=(9, 4.5), dpi=100, facecolor=COLOR_BG_CARD)
        
        # 1. Donut chart: Polled vs Didn't Poll
        ax1 = fig.add_subplot(121)
        ax1.set_facecolor(COLOR_BG_CARD)
        labels = ['Polled', "Didn't Poll"]
        sizes = [data['polled_count'], data['non_polled_count']]
        colors = ['#38BDF8', '#E2E8F0']
        
        wedges, texts, autotexts = ax1.pie(
            sizes, 
            labels=labels, 
            autopct='%1.1f%%', 
            startangle=90, 
            colors=colors,
            textprops={'fontsize': 10, 'color': '#0F172A'},
            wedgeprops=dict(width=0.4, edgecolor='white')
        )
        for autotext in autotexts:
            autotext.set_color('#0F172A')
            autotext.set_weight('bold')
        ax1.set_title("Turnout Participation Rate", fontsize=12, fontweight='bold', color='#0284C7', pad=10)
        
        # 2. Horizontal Bar chart: Votes per dish
        ax2 = fig.add_subplot(122)
        ax2.set_facecolor(COLOR_BG_CARD)
        dish_names = [d['name'][:18] + '...' if len(d['name']) > 18 else d['name'] for d in data['dish_results']][::-1]
        dish_votes = [d['vote_count'] for d in data['dish_results']][::-1]
        
        bars = ax2.barh(dish_names, dish_votes, color='#0284C7', height=0.55, edgecolor='#38BDF8')
        ax2.set_xlabel('Number of Votes', fontsize=10, color='#64748B')
        ax2.set_title("Dish Voting Preference", fontsize=12, fontweight='bold', color='#0284C7', pad=10)
        ax2.spines['top'].set_visible(False)
        ax2.spines['right'].set_visible(False)
        ax2.spines['left'].set_color('#CBD5E1')
        ax2.spines['bottom'].set_color('#CBD5E1')
        ax2.tick_params(colors='#334155', labelsize=9)
        
        for bar in bars:
            width = bar.get_width()
            ax2.text(width + 0.2, bar.get_y() + bar.get_height()/2, f"{int(width)}", 
                     ha='left', va='center', fontsize=9, fontweight='bold', color='#0284C7')
                     
        fig.tight_layout(pad=2.5)
        
        chart_canvas = FigureCanvasTkAgg(fig, master=container)
        chart_canvas.draw()
        chart_canvas.get_tk_widget().pack(fill="both", expand=True)

    # --- TAB 4: AUDIT LOGS ---
    def setup_audit_tab(self):
        container = ctk.CTkFrame(self.tab_audit, fg_color="transparent")
        container.pack(fill="both", expand=True, padx=10, pady=10)
        
        head = ctk.CTkFrame(container, fg_color=COLOR_LIGHT_ACCENT, corner_radius=CORNER_RADIUS_CARD, height=45)
        head.pack(fill="x", pady=(0, 10))
        head.pack_propagate(False)
        
        ctk.CTkLabel(head, text="📜 Complete System & Polling Audit Trail", font=FONT_SUBTITLE, text_color=COLOR_PRIMARY_DARK).pack(side="left", padx=15)
        
        scroll = ctk.CTkScrollableFrame(container, fg_color=COLOR_BG_CARD, border_width=1, border_color=COLOR_BORDER, corner_radius=CORNER_RADIUS_CARD)
        scroll.pack(fill="both", expand=True)
        
        logs = get_audit_logs(limit=40)
        for log in logs:
            row = ctk.CTkFrame(scroll, fg_color=COLOR_BG_CARD_ALT, border_width=1, border_color=COLOR_BORDER_LIGHT, corner_radius=8)
            row.pack(fill="x", padx=10, pady=3)
            
            top_line = ctk.CTkFrame(row, fg_color="transparent")
            top_line.pack(fill="x", padx=10, pady=(6, 2))
            
            action_badge = ctk.CTkFrame(top_line, fg_color=COLOR_LIGHT_ACCENT, corner_radius=6)
            action_badge.pack(side="left")
            ctk.CTkLabel(action_badge, text=log['action'], font=FONT_CAPTION_BOLD, text_color=COLOR_DEEP_OCEAN).pack(padx=6, pady=1)
            
            ctk.CTkLabel(top_line, text=f"By: {log['performed_by']}", font=FONT_CAPTION_BOLD, text_color=COLOR_TEXT_MAIN).pack(side="left", padx=10)
            ctk.CTkLabel(top_line, text=log['timestamp'], font=FONT_CAPTION, text_color=COLOR_TEXT_LIGHT).pack(side="right")
            
            ctk.CTkLabel(row, text=log['details'], font=FONT_BODY, text_color=COLOR_TEXT_MUTED, anchor="w").pack(fill="x", padx=10, pady=(0, 6))

    def export_csv_report(self):
        if not self.selected_poll_id:
            messagebox.showwarning("Export", "No poll selected to export.")
            return
            
        data = get_admin_detailed_data(self.selected_poll_id)
        if not data:
            return
            
        target = filedialog.asksaveasfilename(
            defaultextension=".csv",
            filetypes=[("CSV file", "*.csv")],
            initialfile=f"Hostel_Poll_{self.selected_poll_id}_Report.csv"
        )
        if target:
            with open(target, mode="w", newline="", encoding="utf-8") as f:
                writer = csv.writer(f)
                writer.writerow(["HOSTEL MESS SMART VOTING AUDIT REPORT"])
                writer.writerow(["Poll ID", data['poll']['id']])
                writer.writerow(["Title", data['poll']['title']])
                writer.writerow(["Date", data['poll']['date']])
                writer.writerow(["Meal Type", data['poll']['meal_type']])
                writer.writerow(["Generated By", data['poll']['created_by']])
                writer.writerow(["Expiry Time", data['poll']['expires_at']])
                writer.writerow([])
                writer.writerow(["TURNOUT SUMMARY"])
                writer.writerow(["Total Registered Students", data['total_hostel_students']])
                writer.writerow(["Polled Students", data['polled_count']])
                writer.writerow(["Didn't Poll Students", data['non_polled_count']])
                writer.writerow(["Turnout Percentage", f"{data['turnout_pct']}%"])
                writer.writerow([])
                writer.writerow(["DISH RESULTS"])
                writer.writerow(["Dish Name", "Category", "Votes", "Percentage"])
                for d in data['dish_results']:
                    writer.writerow([d['name'], d['category'], d['vote_count'], f"{d['percentage']}%"])
                writer.writerow([])
                writer.writerow(["STUDENTS WHO POLLED"])
                writer.writerow(["Student ID", "Name", "Room No", "Block", "Chosen Dish", "Vote Timestamp"])
                for s in data['polled_students']:
                    writer.writerow([s['student_id'], s['name'], s['room_no'], s['block'], s['chosen_dish'], s['voted_at']])
                writer.writerow([])
                writer.writerow(["STUDENTS WHO DID NOT POLL"])
                writer.writerow(["Student ID", "Name", "Room No", "Block", "Department", "Phone"])
                for s in data['non_polled_students']:
                    writer.writerow([s['student_id'], s['name'], s['room_no'], s['block'], s['department'], s.get('phone', '')])
                    
            messagebox.showinfo("Export Successful", f"Full admin report exported to:\n{target}")
